module.exports = {
	RECEIVE_DATA: "RECEIVE_DATA",
	MY_EVENT: "MY_EVENT", 
	ONE_VISIBLE: "ONE_VISIBLE",
  	ONE_REMOVE: "ONE_REMOVE",
  	TWO_VISIBLE: "TWO_VISIBLE",
	TWO_REMOVE: "TWO_REMOVE",
	THREE_VISIBLE: "THREE_VISIBLE",
	THREE_REMOVE: "THREE_REMOVE",
	ADUNIT_VISIBLE: "ADUNIT_VISIBLE",
	ADUNIT_REMOVE: "ADUNIT_REMOVE",
	SIDEBAR_VISIBLE: "SIDEBAR_VISIBLE",
	SIDEBAR_REMOVE: "SIDEBAR_REMOVE"    
}

